site_name: PDO dokumentace

theme:
  name: material
  language: cs

  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světlý režim

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Úvod: index.md

  - Základní pojmy:
      - Výlet: koncept/vylet.md
      - Balíčky: koncept/balicky.md

  - Aplikace:
      - Registrace a přihlášení: navody/registrace-a-prihlaseni.md
      - Navigace:
              - Domů: navody/domovska-obrazovka.md
              - Moje výlety: navody/moje-vylety.md
              - Kalendář: navody/pouziti-kalendare.md
              - Statistiky: navody/zobrazeni-statistik.md
              - Šablony balíčků: navody/import-balicku.md
              - Profil: navody/uprava-profilu.md
      - Práce s výlety:
          - Vytvoření výletu: navody/vytvoreni-vyletu.md
          - Detail výletu: navody/detail-vyletu.md
          - Úprava výletu: navody/uprava-vyletu.md
          - Smazání výletu: navody/smazani-vyletu.md





